from PyQt5 import QtCore, QtGui, QtWidgets


class LogWinUI(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(300, 400)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelWelcom = QtWidgets.QLabel(self.centralwidget)
        self.labelWelcom.setGeometry(QtCore.QRect(0, 30, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelWelcom.setFont(font)
        self.labelWelcom.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWelcom.setObjectName("labelWelcom")
        self.lineEditLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLogin.setGeometry(QtCore.QRect(135, 150, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditLogin.setFont(font)
        self.lineEditLogin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.labelLogin = QtWidgets.QLabel(self.centralwidget)
        self.labelLogin.setGeometry(QtCore.QRect(5, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelLogin.setFont(font)
        self.labelLogin.setObjectName("labelLogin")
        self.lineEditPass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPass.setGeometry(QtCore.QRect(135, 190, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditPass.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lineEditPass.setObjectName("lineEditPass")
        self.labelPass = QtWidgets.QLabel(self.centralwidget)
        self.labelPass.setGeometry(QtCore.QRect(5, 190, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelPass.setFont(font)
        self.labelPass.setObjectName("labelPass")
        self.pushButtonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(40, 250, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.checkBoxFPass = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFPass.setGeometry(QtCore.QRect(10, 370, 281, 17))
        self.checkBoxFPass.setObjectName("checkBoxFPass")
        self.pushButtonSignUp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(40, 310, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Survey"))
        self.labelWelcom.setText(_translate("LoginWindow", "Welcom to the Survey system!"))
        self.lineEditLogin.setText(_translate("LoginWindow", "Dr.Hy6yC"))
        self.labelLogin.setText(_translate("LoginWindow", "Login:"))
        self.lineEditPass.setText(_translate("LoginWindow", "Dr.Hy6yC"))
        self.labelPass.setText(_translate("LoginWindow", "Password:"))
        self.pushButtonLogin.setText(_translate("LoginWindow", "Login"))
        self.checkBoxFPass.setText(_translate("LoginWindow", "Click if forgot password"))
        self.pushButtonSignUp.setText(_translate("LoginWindow", "Sign up"))
